# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 618a7562b7cca72e95b1c8aeadeb3eaa82b7e1b33f1c01a501a11d782529e780234fe9ab4f025b0ab836cfb58378ba39f9ed3b62f667f1c7420a96726f36d961

test:
  secret_key_base: 775f0b50b86d67102569af85d7b7a92e92fcca23dcd4dc63e27989e4f2eecbf08be11c1317de55a1ce95a0a51512d9b54f0af0c224cb0c1448fafb7a9be123f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
